### ISSUE TITLE
Questions on Regression Model

### ISSUE THREAD

**Issue by AmandaFranklinRyan** [UniLuFS2020-ReplicationSeminar/Snore#1]
@AngrodAlcarin I just took a look at the regression model and I think it looks great :)  I just had a couple of questions about it. 

Would it be possible to add age, gender and exercise frequency? I plotted a histogram of exercise frequency by gender and it seems that there are very different patterns which could be important for the model. Perhaps there is a similar effect with age too. The adjusted R^2 value is only 0.21 so maybe adding some more independents variables would help. 

I have plotted a series of boxplots showing how sleep efficiency varies with amount of caffeine consumed, but according to the current model there is no statistically significant correlation between caffeine consumption and sleep efficiency. If recalibrating the model doesn't change this maybe it would make more sense to plot alcohol consumption or exercise frequency instead. 

I also noticed that you'd averaged the NAs and I'd dropped them, should I average them in the data visualisation file too?

**Comment by beyzabani** [comment]
@AmandaFranklinRyan hey Amanda, what you did so far is amazing! I'd just like to add that maybe it's better if we remove the caffeine variable. Because apparently people who don't take any caffeine is a large population and the results therefore somehow biased. 
We can still use other variables, especially exercise one, as Andrea was also pretty much interested :D

**Comment by AmandaFranklinRyan** [comment]
@beyzabani Thanks for your suggestion! It makes more sense to use exercise frequency instead. I've just changed the plot and as expected sleep efficiency increases with exercise frequency.

**Comment by AngrodAlcarin** [comment]
Hey guys, thank you so much for your work, that really looks amazing now! I have nothing else to add, outstanding job!
If that's allright with you, I'll close this issue. If not, feel free to reopen it :)
